### PR TITLE
use tokio 1.33 which seems to build on windows.

### LINKED ISSUE #45: ntapi refueses to build if Tokio depedency declared as "1"
Hi and thanks for the app,
I had problem to build from sources on windows and got following error:
```
error[E0793]: reference to packed field is unaligned
    --> C:\Users\viitami\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.6\src\ntexapi.rs:2785:52
     |
2785 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\viitami\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.6\src\ntexapi.rs:2809:25
     |
2809 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` (lib) due to 2 previous errors
```
if updated to latest 1.33, it seems to fix issue.

### PR DESCRIPTION
**Pull request by frogshead**
Fix #45 

Not sure if correct way to fix. And why it was resolved something else than latest?

### CODE REVIEW

**Comment by Hamatti** [comment]
Hey!

Thanks for the PR. Before I merge it in, I'll do a bit of research and ask around to figure out why this actually happens. My assumption would be that version requirement "1" would install the latest so there might be something else happening under the hood.

If you try to build it with version 1 (ie. current main branch), which version of tokio does it actually use?

**Comment by Hamatti** [comment]
Apparently the issue is that I haven't updated my Cargo.lock file in ages. 

Could you try this:

1. Revert this commit (ie. make sure it says `version = "1"` for Tokio
2. Run cargo update
3. Try to build again.

**Comment by frogshead** [comment]
Yes, this does the trick! I am able to build after upate.

**Comment by Hamatti** [comment]
Great! I'll close this PR and make a Cargo.lock update directly.

Thanks for reporting and helping me figure this out, much appreciated! Your contribution made me learn new things about Rust.

**Pull request closed without merging**
